#!/bin/sh
while [ $# -gt 0 ]; do
        case "${1}" in
                help|-h)
                        echo "+++++++++++++++++++++++++++++++++++++++++++++++++++++"
                        echo "Simple POSIX shell password generator using urandom."
                        echo "Generates 100 passwords and dumps them in ~/password." 
                        echo "Thanks to Ella-0 for POSIX shell compatiblity &"
                        echo "NotGrey for the make ~/passwords overwrite and"
                        echo "only readable by you and root command &"
                        echo "Breadtard for the options"
                        echo "options: -l & -c specify length or charset"
                        echo "Usage"
                        echo "help or -h   display this message"
                        echo "where or -w    display where the script is"
                        echo "-l{} & -c[] specify {length} or [charset]"
                        echo "====================================================="
                        exit 0
                        ;;
                where|-w)
                        script=$(dirname "$0")
                        echo $script
                        exit 0
                        ;;
                -l) LEN=${OPTARG}     ;;
	        -c) CHARSET=${OPTARG};;
        esac
        shift
done

if [ -z "$LEN" ]; then
	LEN=64
fi

if [ -z "$CHARSET" ]; then
	echo $(cat /dev/urandom | head | base64) | sed -e "s/ //g" | fold -w$LEN | head -n1
else
	echo $(cat /dev/urandom | head | base64) | sed -e "s/ //g" | fold -w1 | grep "[$CHARSET]" | xargs | sed -e "s/ //g" | fold -w$LEN | head -n1
fi
LEN=
CHARSET=
echo "Passwords Generated"
